### ISSUE TITLE
formcontrol tidak terbaca

### ISSUE THREAD

**Issue by yozzaamandha** [faridsurya-uad/angular#1]
tadi kan, saya sudah import formcontrol module di admin module.ts pak, nah dia error pak, setelah itu, ngIf di saya juga error pak, itu solusinya bagaimana ya pak?

**Comment by yozzaamandha** [comment]
![photo_2021-04-15_18-05-24](https://user-images.githubusercontent.com/76605299/114859615-3247cc00-9e15-11eb-8520-3fad59457b6f.jpg)

**Comment by yozzaamandha** [comment]
![photo_2021-04-15_18-06-05](https://user-images.githubusercontent.com/76605299/114859665-4390d880-9e15-11eb-8d87-05db513fbaa9.jpg)

**Comment by gallangsdw** [comment]
coba konfigurasi pada package.json

```
{
  "scripts": {
    "postinstall": "ngcc"
  }
}
```

**Comment by gallangsdw** [comment]
referensi selengkapnya bisa liat di https://angular.io/guide/ivy

**Comment by hendra136** [comment]
saya ijin bertanya pak., setelah melihat video 5 bagian 2 di menit ke 13 tentang fungsi button menambahkan data. kenapa button saya tidak bisa berungsi ya pak. padahal di koding tidak ada eror dan kodingnya dari awal saya mengikuti vdeio bapak dari vdeio k5 bagian 1 dan 2

**Comment by hendra136** [comment]
bertanya lagi, cara mengatasi warna web yang terbalik dimana ya. contoh kasusnya pada tulisanya warna backgrounnya abu" dan background dasarnya warna putih. yang semestinya bacground tulisanya warna putih dan background dari layarnya abu abu

**Comment by yozzaamandha** [comment]
![image](https://user-images.githubusercontent.com/76605299/115138722-08321c00-a058-11eb-8691-a389b7d079e5.png)
permisi kakak asprak, saya mau tanya, kan saya dah konfigurasi pada package.json, dan mengkonfigurasi ivy juga, tapi kok error yah kak?

**Comment by faridsurya-uad** [comment]
ada masalah di app.module.ts jadi sertakan juga kode di app.module.ts
