### ISSUE TITLE
Autentikasi PUT dan DELETE yang belum berhasil

### ISSUE THREAD

**Issue by ifarifah** [faridsurya-uad/angular#10]
Permasalahan :
- Pada saat edit data, data yang sudah diedit dan yang asli muncul secara bersamaan.
- Pada saat ingin melakukan delete data, data berhasil didelete tetapi saat direload data tersebut muncul kembali.

![Screenshot_2](https://user-images.githubusercontent.com/80370577/115336039-988f6e80-a1c8-11eb-8d85-849a8ff76bf6.png)

**Comment by ifarifah** [comment]
Perbaikan :
Pastikan id mengarah ke tujuannya

![Screenshot_9](https://user-images.githubusercontent.com/80370577/115336519-97ab0c80-a1c9-11eb-960b-8d72c0f32090.png)


![Screenshot_10](https://user-images.githubusercontent.com/80370577/115336540-9ed21a80-a1c9-11eb-8fca-fe02940a15c8.png)

**Comment by ifarifah** [comment]
Respon jika data berhasil di PUT dan di DELETE

![Screenshot_5](https://user-images.githubusercontent.com/80370577/115336641-c628e780-a1c9-11eb-833e-c091ae2a8048.png)


![Screenshot_6](https://user-images.githubusercontent.com/80370577/115336661-ccb75f00-a1c9-11eb-8d3e-aac73b057274.png)

**Comment by gallangsdw** [comment]
well done!

**Comment by faridsurya-uad** [comment]
Bagi yang dapet masalah serupa, silahkan ikuti ini.
