### ISSUE TITLE
Tidak bisa update data (video 6)

### ISSUE THREAD

**Issue by hendra136** [faridsurya-uad/angular#2]
ijin bertanya mas, saya sudah memasuki video ke 6 yang memasukan api. tapi waktu saya save dan run ngk ada eror tapi hasilnya ngk muncul produknya mas. aapakah ini berpengaruh dari sinyal atau gimana ya mas

**Comment by hendra136** [comment]
![image](https://user-images.githubusercontent.com/75875744/115187589-c499e980-a10d-11eb-9336-4779284862c6.png)
ijin bertanya mas, ini kenapa malah eror ngirim datanya ya mas

**Comment by faridsurya-uad** [comment]
Kalau soal komunikasi data dengan server, kasih ss di bagian network biar yang mau jawab tahu permasalahannya.

**Comment by hendra136** [comment]
Baik pak. Segera saya masukan

**Comment by hendra136** [comment]
![Uploading image.png…]()
maaf pak ini foto ss nya. masalahnya tidak bisa edit dan simpan pak

**Comment by hendra136** [comment]
begitu juga dengan delete pak

**Comment by hendra136** [comment]
![image](https://user-images.githubusercontent.com/75875744/115230740-f37c8380-a13e-11eb-9125-df3858b0b5fe.png)

**Comment by hendra136** [comment]
![image](https://user-images.githubusercontent.com/75875744/115252135-655fc780-a155-11eb-88a6-11ce935cbc21.png)
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  serverUrl:any='http://api.sunhouse.co.id/bookstore/index.php/';
  constructor(
    public http:HttpClient
  ) { }
  get (url: any)
  {
    return this.http.get(this.serverUrl+url);
  }
  post(url: any,data: any)
  {
   return this.http.post(this.serverUrl+url,data);
  }
  put(url: any,data: any)
  {
   return this.http.put(this.serverUrl+url,data);
  }

}

**Comment by hendra136** [comment]
![Uploading image.png…]()
import { Component, Inject, OnInit } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-product-detail',
  templateUrl: './product-detail.component.html',
  styleUrls: ['./product-detail.component.css']
})
export class ProductDetailComponent implements OnInit {

  constructor(
    public dialogRef:MatDialogRef<ProductDetailComponent>,
   @Inject(MAT_DIALOG_DATA) public data: any,
   public api:ApiService

  ) { }

  ngOnInit(): void {
  }
  saveData()
 {
  if(this.data.id == undefined){
    this.api.post('books',this.data).subscribe(result=>{
      this.dialogRef.close(result);
    });
   }else{
    this.api.post('books/'+this.data.id,this.data).subscribe(result=>{
      this.dialogRef.close(result);
      console.log(result);
    })
  }
   
 }
}

**Comment by hendra136** [comment]
![Uploading image.png…]()
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { ApiService } from 'src/app/services/api.service';
import { ProductDetailComponent } from '../product-detail/product-detail.component';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent implements OnInit {
  title: any;
  book:any={};
  books: any=[];
  constructor(
    public dialog:MatDialog,
    public api:ApiService
  ) {
    this.title='product';
    
  }  
  ngOnInit(): void {
    this.getBooks();
  }
  
  getBooks()
  {
  this.api.get('books').subscribe(result=>{
    this.books=result;
  })
}

productDetail(data: any,idx: number)
 {
   let dialog=this.dialog.open(ProductDetailComponent, {
     width:'400px',
     data:data
   });
   dialog.afterClosed().subscribe((res: any)=>{
     if(res)
     {
        //jika idx=-1 (penambahan data baru) maka tambahkan data
       if(idx==-1)this.books.push(res);      
        //jika tidak maka perbarui data  
       else this.books[idx]=data; 
     }
   })
 }
 deleteProduct(idx: any)
 {
   var conf=confirm('Mau Hapus Ngk ?');
   if(conf)
   this.books.splice(idx,1);
 }
}

**Comment by hendra136** [comment]
berikut ini koding dari 3 komponen yang berhubungan di video 6 pak

**Comment by hendra136** [comment]
![image](https://user-images.githubusercontent.com/75875744/115254716-d30cf300-a157-11eb-9782-0e056a90a289.png)
berikut ini foto percobaan kedua pak

**Comment by hendra136** [comment]
![Uploading image.png…]()


saveData()
 {
  if(this.data.id == undefined){
    this.api.post('books',this.data).subscribe(result=>{
      this.dialogRef.close(result);
    });
   }else{
    this.api.put('books/'+this.data.id,this.data).subscribe(result=>{
      this.dialogRef.close(result);
      console.log(result);
    })
  }
   
 }
}



ini saya ganti put menjadi post pak

**Comment by faridsurya-uad** [comment]
Kode pada app-product.detail.ts
`
saveData()
 {
   this.loading=true;
   if(this.data.id == undefined)
   {
    this.api.post('bookswithauth',this.data).subscribe(result=>{
      this.dialogRef.close(result);
      this.loading=false;
     },error=>{
      this.loading=false;
      alert('Tidak dapat menyimpan data');
     });
   }else{
     this.api.put('bookswithauth/'+this.data.id,this.data).subscribe(result=>{
      this.dialogRef.close(result);
      this.loading=false;
     },error=>{
      this.loading=false;
      alert('Tidak dapat memperbarui data');
     })
   }
  
   
 }

`

**Comment by hendra136** [comment]
saveData()
 {
  if(this.data.id == undefined){
    this.api.post('books',this.data).subscribe(result=>{
      this.dialogRef.close(result);
    });
   }else{
    this.api.put('books/'+this.data.id,this.data).subscribe(result=>{
      this.dialogRef.close(result);
      console.log(result);
    })
  }
   
 }
}



ini saya ganti put menjadi post pak

**Comment by hendra136** [comment]
![image](https://user-images.githubusercontent.com/75875744/115257314-2bdd8b00-a15a-11eb-96e3-064b07f6645b.png)
berikut ini fotonya pak

**Comment by hendra136** [comment]
![image](https://user-images.githubusercontent.com/75875744/115257638-77903480-a15a-11eb-9735-f050c9d7dc68.png)
berikut ini foto dari mengganti post menjadi put pak

**Comment by hendra136** [comment]
> this.api.post('bookswithauth',this.data).subscribe(result=>{
> this.dialogRef.close(result);
> this.loading=false;
> },error=>{
> this.loading=false;
> alert('Tidak dapat menyimpan data');
> });
> }else{
> this.api.put('bookswithauth/'+this.data.id,this.data).subscribe(result=>{
> this.dialogRef.close(result);
> this.loading=false;
> },error=>{
> this.loading=false;
> alert('Tidak dapat memperbarui data');
> })

maaf pak saya sudah memasukan koding ini tapi tetap sama pak.malah terjadi eror seperti yang saya kirimkan di atas sebelumnya pak

**Comment by hendra136** [comment]
![IMG-20210420-WA0060](https://user-images.githubusercontent.com/75875744/115417170-fce31a00-a22a-11eb-827e-250903acb9be.jpeg)
Alhamdulillah bisa pak. Solusinya ada pada put di api service yg awalnya any di ganti string pak. Serta harus pakai console supaya bisa button simpan berfungsi

**Comment by hendra136** [comment]
import { Component, Inject, OnInit } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-product-detail',
  templateUrl: './product-detail.component.html',
  styleUrls: ['./product-detail.component.css']
})
export class ProductDetailComponent implements OnInit {

  constructor(
    public dialogRef:MatDialogRef<ProductDetailComponent>,
   @Inject(MAT_DIALOG_DATA) public data: any,
   public api:ApiService

  ) { }

  ngOnInit(): void {
  }
  saveData()
 {
  if(this.data.id == undefined){
    this.api.post('books',this.data).subscribe(result=>{
      this.dialogRef.close(result);
    },error=>{
      alert(error)
     });
   }else{
    this.api.put('books/'+this.data.id,this.data).subscribe(result=>{
      this.dialogRef.close(result);
      console.log(result);
    },error=>{
      alert(error);
     })
  }
   
 }
}

**Comment by hendra136** [comment]
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  serverUrl:any='http://api.sunhouse.co.id/bookstore/index.php/';
  constructor(
    public http:HttpClient
  ) { }
  get (url: any)
  {
    return this.http.get(this.serverUrl+url);
  }
  post(url: any,data: any)
  {
   return this.http.post(this.serverUrl+url,data);
  }
  put(url: string,data: any)
  {
   return this.http.put(this.serverUrl+url,data);
  }

}
perbaikan pada put url : string

**Comment by faridsurya-uad** [comment]
Setiap sudah solved di beritahu disini, good! biar orang lain bisa belajar dari kesalahan serupa.
