### ISSUE TITLE
Error saat connect ke MyAngular

### ISSUE THREAD

**Issue by fikriAuliani** [faridsurya-uad/angular#3]
saat akan connect ke Angular pertama kali ada error :

Error: src/app/admin/admin/admin.component.html:16:16 - error TS2322: Type 'string' is 
not assignable to type 'MatDrawerMode'.

16       #sidenav mode="{{mode}}"
                  ~~~~

  [src/app/admin/admin/admin.component.ts:5:16]
    5   templateUrl: './admin.component.html',

                     ~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AdminComponent.

``
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

**Comment by faridsurya-uad** [comment]
sertakan kode pada admin.component.ts dan admin.component.html

**Comment by fikriAuliani** [comment]
kode admin.component.html: 

<ng-container>
    
    <mat-toolbar color="primary" class="example-header">
        <button mat-icon-button (click)="sidenav.toggle()">
            <mat-icon>menu</mat-icon>
        </button>
        <span>My Angular</span>
        <div class="uk-width-expand"></div>
        <small>Admin</small>
    </mat-toolbar>
    
    
    <mat-sidenav-container class="admin-container">
    
      <mat-sidenav 
      #sidenav mode="{{mode}}" 
      [position]="'start'" 
      opened class="sidenav-left"
      [fixedInViewport]="true" 
      [fixedTopGap]="60"
      [fixedBottomGap]="0">
    
      <mat-nav-list>
        <mat-list-item routerLink="/admin/dashboard">
            <mat-icon matListIcon>dashboard</mat-icon>
            <h3 matLine>Dashboard</h3>
        </mat-list-item>
        <mat-list-item routerLink="/admin/images">
            <mat-icon matListIcon>camera enhance</mat-icon>
            <h3 matLine>Edit Image</h3>
        </mat-list-item>
       </mat-nav-list>
    
      </mat-sidenav>
    
    <mat-sidenav #sidenav mode="side" [position]="'end'"  class="example-sidenav"
    [fixedInViewport]="true" [fixedTopGap]="60"
    [fixedBottomGap]="0">
    
       
    
    </mat-sidenav>
    
    <mat-sidenav-content style="padding: 20px; background-color: #ccc;">
    
        <router-outlet></router-outlet>
    </mat-sidenav-content>
    
    </mat-sidenav-container>   
    </ng-container>

kode admin.component.ts: 

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AdminComponent } from './admin/admin.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { Routes, RouterModule} from '@angular/router';
import {MaterialDesign} from '../material/material.module';
import { ImagesComponent } from './images/images.component';

const routes: Routes = [
  {
    path:'',
    component:AdminComponent,
    children:[
      {
        path:'dashboard',
        component:DashboardComponent
      },
      {
        path:'',
        pathMatch:'full',
        redirectTo:'/admin/dashboard'
      }
    ]
  }
]

@NgModule({
  declarations: [AdminComponent, DashboardComponent, ImagesComponent],
  imports: [
    CommonModule,
    RouterModule.forChild(routes),
    MaterialDesign
  ]
})
export class AdminModule { }

**Comment by faridsurya-uad** [comment]
coba:

` mode="{{mode}}" `

ganti dengan:

` [mode]="mode" `

**Comment by fikriAuliani** [comment]
jadi error pak :

Error: src/app/admin/admin/admin.component.html:16:17 - error TS2322: Type 'string' is not assignable to type 'MatDrawerMode'.

16       #sidenav [mode]="mode"
                   ~~~~

  src/app/admin/admin/admin.component.ts:5:16
    5   templateUrl: './admin.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AdminComponent.

**Comment by fikriAuliani** [comment]
![error2](https://user-images.githubusercontent.com/76683491/115257096-fcc71980-a159-11eb-9d88-5aea69ef2aff.JPG)

**Comment by fikriAuliani** [comment]
![admin component ts](https://user-images.githubusercontent.com/76683491/115262712-fd15e380-a15e-11eb-9650-3ad9fc917147.JPG)

**Comment by faridsurya-uad** [comment]
solusi:

hapus dulu `[mode]="mode"`

**Comment by fikriAuliani** [comment]
Solve ternyata saya salah ketik pak, Solusinya :
#sidenav mode="side"
