### ISSUE TITLE
di bagian admin "MENU" dan "MY ANGULAR" nya tumpuk kak.. tolong solusinya..terimakasih

### ISSUE THREAD

**Issue by falah-maulana** [faridsurya-uad/angular#5]
![image](https://user-images.githubusercontent.com/76674665/115263091-51b95e80-a15f-11eb-8d26-5860a3a669be.png)

**Comment by gallangsdw** [comment]
silahkan dilampirkan kode `styles.scss` nya

**Comment by faridsurya-uad** [comment]
sepertinya typo di toogle

harusnya `(click)="sidenav.toggle()"`

**Comment by falah-maulana** [comment]
nggeh sampun pak, mas... matur suwun sanget

**Comment by faridsurya-uad** [comment]
@gallangsdw kalau issue sudah solved, maka di close.
