### ISSUE TITLE
eror dibagian <mat-icon>menu</mat-icon> admin component html

### ISSUE THREAD

**Issue by octaviya1900016166** [faridsurya-uad/angular#9]
itu gimana ya mas saya cek kodingannya sepertinya juga sudah benar

![eror](https://user-images.githubusercontent.com/82858338/115335620-bd371680-a1c7-11eb-902c-9e9a1e2795d3.PNG)

**Comment by octaviya1900016166** [comment]
<ng-container>
    
    <mat-toolbar color="primary" class="example-header">
          <button mat-icon-button (click)="sidenav.toggle()">
             <mat-icon>menu</mat-icon>
         </button>
        <span>octa-angular</span>
        <div class="uk-width-expand"></div>
        <small>Admin</small>
    </mat-toolbar>
    
    
    <mat-sidenav-container class="admin-container">    
        <mat-sidenav
         #sidenav
         mode="side"
         [position]="'start'" 
         [opened]="false"
         class="sidenav-left"
        [fixedInViewport]="true" 
        [fixedTopGap]="63"
        [fixedBottomGap]="0">
      
        <mat-nav-list>
              <mat-list-item routerLink="/admin/dashboard">
                  <mat-icon matListIcon>dashboard</mat-icon>
                  <h3 matLine>Dashboard</h3>
              </mat-list-item>
              <mat-list-item routerLink="/admin/images">
                  <mat-icon matListIcon>camera_enhance</mat-icon>
                  <h3 matLine>Edit images</h3>
              </mat-list-item>
  
         </mat-nav-list>
      
        </mat-sidenav>
      
      <mat-sidenav #sidenav mode="side" [position]="'end'"  class="example-sidenav"
      [fixedInViewport]="true" [fixedTopGap]="60"
      [fixedBottomGap]="0">
      
         
      
      </mat-sidenav>
      
      <mat-sidenav-content style="padding: 20px; background-color: #ccc;">
      
            <router-outlet></router-outlet>
      </mat-sidenav-content>
      
      </mat-sidenav-container>   
    </ng-container>

**Comment by gallangsdw** [comment]
good job! keep it up

**Comment by octaviya1900016166** [comment]
tapi itu belum bisa mas di browasernya maasih cannot get gitu
![image](https://user-images.githubusercontent.com/82858338/115338075-56682c00-a1cc-11eb-95d1-7143fee09760.png)

**Comment by faridsurya-uad** [comment]
Coba pakai ini:

```
<div class="example-container">
  <mat-toolbar color="primary" class="example-toolbar">
    <button mat-icon-button (click)="snav.toggle()"><mat-icon>menu</mat-icon></button>
    <h1 class="example-app-name">Responsive App</h1>
  </mat-toolbar>

  <mat-sidenav-container class="example-sidenav-container"
                         [style.marginTop.px]="56">
    <mat-sidenav #snav [mode]="'side'"
                 [fixedInViewport]="true" fixedTopGap="56">
      <mat-nav-list>
        <a mat-list-item routerLink=".">Dashboard</a>
      </mat-nav-list>
    </mat-sidenav>

    <mat-sidenav-content>
      <h1>Welcome</h1>
    </mat-sidenav-content>
  </mat-sidenav-container>
</div>
```

Referensi: [https://material.angular.io/components/sidenav/examples](url)
